name: Deploy Doxygen PDF
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout repository
        uses: actions/checkout@v2

      # Step 2: Install Doxygen
      - name: Install Doxygen
        run: sudo apt-get install -y doxygen

      # Step 3: Install Graphviz for diagrams (if needed by Doxygen)
      - name: Install Graphviz
        run: sudo apt-get install -y graphviz

      # Step 4: Generate Doxygen documentation (this assumes you have a Doxyfile in your repo)
      - name: Run Doxygen
        run: doxygen Doxyfile

      # Step 5: Use the LaTeX container to generate the PDF from the LaTeX files produced by Doxygen
      - name: Generate PDF using LaTeX Action
        uses: xu-cheng/latex-action@v2
        with:
          working_directory: docs/latex/
          root_file: refman.tex

      # Step 6: Copy the generated PDF to a folder for deployment
      - name: Copy PDF to output folder
        run: |
          mkdir out
          cp ./docs/latex/refman.pdf ./out/refman.pdf

      # Step 7: Upload the PDF as an artifact for download from the Actions tab
      - uses: actions/upload-artifact@v3
        with:
          name: Doxygen-PDF
          path: out/refman.pdf
